/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/policies/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compile the customer's instruction into a local draft */
        post: operations["createDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/drafts/{draft_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a sourced chat exchange without changing permission or revision */
        post: operations["recordDraftMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/drafts/{draft_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer clarifying questions; accepted answers add to the draft */
        post: operations["answerDraftQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/drafts/{draft_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add what the customer said next; the whole instruction is read again (LEASH-145)
         * @description A conversation turn, not an answer to a question. The text is added to the customer's own words and the draft is recompiled as a new revision; an earlier answer whose question is no longer open is dropped from the replay and asked again, never applied to another question.
         */
        post: operations["addDraftTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/drafts/{draft_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post the finished policy to Viseca as a platform draft */
        post: operations["submitDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/drafts/{draft_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Customer confirms; the mandate becomes active (idempotent) */
        post: operations["confirmDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reload a local draft (e.g. after reconnecting mid-clarification) */
        get: operations["getDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mandates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All mandates and which one is current */
        get: operations["listMandates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mandates/{mandate_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version history: confirmations, tightenings, revocation */
        get: operations["listMandateVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mandates/{mandate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current permission */
        get: operations["getMandate"];
        put?: never;
        post?: never;
        /** Revoke the agent's permission */
        delete: operations["revokeMandate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mandates/{mandate_id}/tighten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append stricter rules or switch uncertainty to decline */
        post: operations["tightenMandate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the scenario catalogue from the connected simulator */
        get: operations["listScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs, newest first, and which one is in progress */
        get: operations["listRuns"];
        put?: never;
        /** Start a scenario run with the active mandate */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run progress */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent payments with engine verdict and final outcome */
        get: operations["listPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{authorization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One payment: checks, evidence, shop text and what was sent */
        get: operations["getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Payments waiting for the customer */
        get: operations["listAsks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asks/{authorization_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Customer approves or rejects a waiting payment */
        post: operations["answerAsk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending against the period limit, cross-checked with the platform counter */
        get: operations["getSpending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events; payloads are StreamEvent (see events.md) */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ScenarioList: {
            scenarios: {
                scenario_id: string;
                scenario_name: string;
                cardholder_instruction: string;
                event_count: number;
                /** @description One line saying what this demonstration shows, from our copy of the supplied catalogue, joined by scenario ID. Absent when we hold no note for it (LEASH-147). */
                summary?: string;
                /** @description The demonstration to open with. At most one scenario carries it. */
                recommended?: boolean;
            }[];
        };
        /** @description One boundary in the customer's words, with the heading it is read under (LEASH-146). The text is generated from the stored rule, never from model prose (DEC-045). */
        ReviewLine: {
            text: string;
            /** @enum {string} */
            group: "item" | "price" | "merchant" | "frequency" | "uncertainty";
        };
        PermissionReview: {
            must_follow: components["schemas"]["ReviewLine"][];
            /** @description Includes every registry field this permission places no rule on, named in plain words: a restriction the model silently dropped is otherwise invisible (DEC-045). */
            may_choose: components["schemas"]["ReviewLine"][];
            must_ask: components["schemas"]["ReviewLine"][];
        };
        AssistantAssessment: {
            history_checked?: string;
            model?: string;
            prompt_version?: string;
            status?: string;
            /** @enum {string} */
            reading?: "reference" | "model";
            /** @enum {string} */
            uncertainty_policy?: "ask" | "decline";
            questions?: (string | ({
                text: string;
                options?: string[];
            } & {
                [key: string]: unknown;
            }))[];
        } & {
            [key: string]: unknown;
        };
        /** @description Decimal amount as a string, two decimals (never a JSON number). */
        Money: string;
        /** @description Same shape as the Viseca API's errors. */
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        /** @description Exactly the Viseca rule format. Our own fields use the versioned `leash.` registry (DEC-004). */
        HardRule: {
            field: string;
            /** @enum {string} */
            operator: "<" | "<=" | "=" | "!=" | ">" | ">=" | "in" | "not_in";
            value: number | string | string[];
            /** @enum {string|null} */
            currency?: "CHF" | "EUR" | "GBP" | "USD" | null;
            /** @enum {string|null} */
            scope?: "purchase" | "period" | null;
            period_days?: number | null;
        };
        /** @description One rule in plain language, as shown to the customer. */
        RuleView: {
            text: string;
            /** @enum {string} */
            source: "viseca" | "team" | "assumption" | "customer";
            /** @description DEC- id when the reading comes from the decision log */
            decision?: string | null;
            tightened: boolean;
        };
        Question: {
            question_id: string;
            text: string;
            options?: string[];
            blocking: boolean;
            /** @description The rule this question is about, when it is about one. It lets a caller ask the question in the customer's own terms; answering it is what may create a rule. */
            field?: string | null;
            /**
             * @description Whose words this question is in. `leash` (the default when absent) is generated from a rule or a registry field; `model` is the permission assistant's own prose, carried as provenance and never as consent text (DEC-045, LEASH-174). A caller must not present the two alike.
             * @enum {string}
             */
            origin?: "leash" | "model";
            /** @description Where the question came from, when it came from the customer's background rather than from their own words. Absent for every question their instruction prompted. Background suggests questions and never grants authority (DEC-034), so a question it put here must say so: unattributed, it reads to the customer as something they already agreed to. `evidence` is the recorded wording itself, so the screen can quote it and the customer can disagree with the actual words rather than a paraphrase. */
            source?: {
                /** @enum {string} */
                kind: "preference" | "history" | "statement" | "confirmed";
                evidence: string;
                file?: string | null;
                row_id?: string | null;
            } | null;
        };
        CreateDraftRequest: {
            instruction: string;
            /** @description Rules the permission assistant read from the customer's words (DEC-045). They are appended like any other rule, so the strictest per field still wins and a draft can only get tighter. Each is validated against the registry here; anything unreadable is refused, never stored. */
            rules?: components["schemas"]["HardRule"][];
        };
        /** @description Local draft: not yet sent to Viseca (DEC-003, LEASH-123). */
        PolicyDraft: {
            /** @description Task text submitted with the reviewed rules. For simulations this preserves the original scenario instruction; clarification turns remain in the conversation. */
            mandate_instruction?: string;
            /** @description Stored conversation snapshots in revision order, including superseded drafts. Read-only history, never active rules. */
            revisions?: components["schemas"]["PolicyDraft"][];
            customer_turn?: {
                text: string;
                replaced: boolean;
            };
            messages?: {
                text: string;
                reply: string;
                revision: number;
                context: {
                    [key: string]: unknown;
                };
            }[];
            simulation_scenario?: string;
            confirmed_mandate?: components["schemas"]["Mandate"];
            review?: components["schemas"]["PermissionReview"];
            assistant?: components["schemas"]["AssistantAssessment"];
            draft_id: string;
            /** @description Which revision of this draft you are looking at (LEASH-101). A correction before activation creates the next revision and marks the previous one superseded; submit and confirm require the revision that was reviewed and refuse a stale one. */
            revision: number;
            instruction: string;
            /** @enum {string} */
            status: "needs_answers" | "ready";
            rules: components["schemas"]["RuleView"][];
            hard_rules: components["schemas"]["HardRule"][];
            /** @enum {string} */
            uncertainty_policy: "ask" | "decline" | "approve";
            notes: string[];
            /** @description The rules the caller supplied when the draft was created, remembered so a later turn or answer recompiles with them (DEC-045). Forgetting them would silently drop restrictions the customer has already seen, which is a loosening. */
            proposed?: components["schemas"]["HardRule"][];
            /** @description The rules this service read from the instruction and answers on its own, without the `rules` the caller supplied (DEC-045). A caller gets its own proposal back inside `hard_rules`, so only this shows whether the deterministic reading agreed independently. */
            independently_read?: components["schemas"]["HardRule"][];
            /** @description Registry fields this draft places no rule on (DEC-045). The model reads the customer's words, so a restriction it silently drops leaves every rule shown correct and the omission invisible; the review names these so the customer can spot what is missing. */
            unrestricted?: string[];
            /** @description The answers this draft view was actually built from, in replay order (LEASH-145). A turn can drop an earlier answer when its question closed or was re-asked under another id. Earlier answers remain in revisions for the conversation history. */
            answers?: {
                question_id: string;
                /** @description The question as it was worded when it was answered. */
                question: string;
                answer: string;
            }[];
            open_questions: components["schemas"]["Question"][];
        };
        TurnRequest: {
            /** @description Background evidence read for this revision; never grants authority. */
            context?: {
                [key: string]: unknown;
            } | null;
            /** @description Replace the unsubmitted task; earlier revisions remain in the audit record. */
            replace_instruction?: boolean;
            /** @description Required for a complete model proposal. Rejects the write if the draft changed since this revision was read. */
            expected_revision?: number;
            assessment?: components["schemas"]["AssistantAssessment"];
            /** @description The customer's own words. Never agent or merchant text. */
            text: string;
            /** @description Registry-validated rules. Model proposals supply the complete revised draft bound to expected_revision; reference proposals append to what the draft already holds. */
            rules?: components["schemas"]["HardRule"][];
        };
        AnswersRequest: {
            answers: {
                question_id: string;
                answer: string;
            }[];
        };
        /** @description Exactly what was posted to Viseca; shown to the customer before confirming. */
        PlatformDraft: {
            review?: components["schemas"]["PermissionReview"];
            draft_id: string;
            platform_draft_id: string;
            instruction: string;
            hard_rules: components["schemas"]["HardRule"][];
            /** @enum {string} */
            uncertainty_policy: "ask" | "decline" | "approve";
            guidance: string[];
            open_questions?: string[];
        };
        ConfirmRequest: {
            /** @constant */
            confirmed: true;
            /** @description The required reviewed revision; stale revisions are refused with 409 stale_revision. */
            revision: number;
        };
        /** @description The exact reviewed draft revision. */
        SubmitRequest: {
            /** @description The required reviewed revision; stale revisions are refused with 409 stale_revision. */
            revision: number;
        };
        Mandate: {
            review?: components["schemas"]["PermissionReview"];
            mandate_id: string;
            version: number;
            /** @enum {string} */
            status: "active" | "revoked" | "expired";
            instruction: string;
            rules: components["schemas"]["RuleView"][];
            hard_rules: components["schemas"]["HardRule"][];
            /** @enum {string} */
            uncertainty_policy: "ask" | "decline" | "approve";
            /** @description Changes apply to runs started after this version (DEC-006). */
            applies_from?: string;
            revocation?: {
                platform_confirmed?: boolean;
                note?: string | null;
            } | null;
        };
        /** @description Only stricter changes: rules are appended, uncertainty can only move to decline (DEC-006). */
        TightenRequest: {
            /** @description Reject with stale_version if the permission changed since review. */
            expected_version?: number;
            add_hard_rules?: components["schemas"]["HardRule"][];
            /** @constant */
            uncertainty_policy?: "decline";
        };
        StartRunRequest: {
            scenario_id: string;
            mandate_id: string;
        };
        Run: {
            run_id: string;
            scenario_id: string;
            mandate_id: string;
            mandate_version: number;
            /** @enum {string} */
            status: "running" | "finished" | "failed";
            counters?: {
                [key: string]: number;
            };
        };
        Payment: {
            authorization_id: string;
            /**
             * @description What the platform did with our decision, kept apart from the decision itself (LEASH-130). `pending` — decided and submitted, not yet acknowledged. `accepted` — the platform accepted the decision; that is all it means, and never that anything was settled, shipped or delivered. `refused` — terminally refused (for example `deadline_passed`); the purchase is then `not_sent` and counts toward nothing.
             * @enum {string}
             */
            delivery: "pending" | "accepted" | "refused";
            /** @description Platform response, or conflict:&lt;status&gt; when reconciliation found a disagreement. Null while pending. */
            platform_outcome: string | null;
            source_authorization_id?: string | null;
            run_id: string;
            merchant: {
                merchant_id: string;
                name: string;
                category: string;
                country: string;
                city?: string;
            };
            /**
             * Format: date-time
             * @description Simulated purchase time
             */
            sim_time: string;
            amount: components["schemas"]["Money"];
            /** @enum {string} */
            currency: "CHF" | "EUR" | "GBP" | "USD";
            billing_amount_chf: components["schemas"]["Money"];
            items: {
                item_id: string;
                name: string;
                quantity: number;
                unit_price?: components["schemas"]["Money"];
            }[];
            /** @enum {string|null} */
            engine_verdict: "approve" | "decline" | "step_up" | null;
            /**
             * @description What the engine decided, and what the customer or the platform did about it. Read it with `delivery`, never alone: approved+accepted is shown as "Approved" — never "Paid", because the platform accepting a decision says nothing about settlement — approved+pending as "Approved · sending", waiting as "Waiting for you", declined as "Blocked", timed_out as "No answer". `not_sent` is either a purchase the platform rejected before it reached the engine (no verdict, e.g. permission revoked) or a decision it terminally refused (delivery `refused`); the two read differently in the app.
             * @enum {string}
             */
            final_state: "approved" | "declined" | "waiting" | "timed_out" | "not_sent";
            /** @enum {string|null} */
            resolved_by: "engine" | "customer" | "platform" | null;
            customer_message: string;
        };
        PaymentList: {
            payments: components["schemas"]["Payment"][];
        };
        Check: {
            key: string;
            label: string;
            /** @enum {string} */
            status: "pass" | "fail" | "warn" | "info" | "integrity";
            agreed: string;
            actual: string;
            detail: string;
            reason_code?: string | null;
        };
        /** @description One check as a fact supporting the decision, in the words the customer was shown. */
        Evidence: {
            /** @description The check's stable key, e.g. "price". */
            check: string;
            label: string;
            /** @enum {string} */
            status: "pass" | "fail" | "warn" | "integrity";
            agreed: string;
            actual: string;
            reason_code: string | null;
        };
        PaymentDetail: components["schemas"]["Payment"] & {
            checks: components["schemas"]["Check"][];
            /** @description One object per non-info check, exactly as sent to the platform, which validates this field as a list of objects and refuses a list of strings. */
            evidence: components["schemas"]["Evidence"][];
            /** @description Merchant text: untrusted, render as plain text. */
            shop_texts: {
                item_id: string;
                text: string;
            }[];
            /** @description The body POSTed to /v1/authorizations/{id}/decision; null when nothing was sent. */
            sent_to_viseca: Record<string, never> | null;
            engine_version: string;
            reader: {
                name: string;
                model_unavailable: boolean;
            };
        };
        Ask: {
            authorization_id: string;
            payment: components["schemas"]["Payment"];
            reasons: string[];
            passed: string[];
            /**
             * Format: date-time
             * @description Real clock; the app counts down from this (DEC-008).
             */
            expires_at: string;
            /** @description False when a hard rule now fails (DEC-012). */
            can_approve: boolean;
            cannot_approve_reason: string | null;
        };
        AskList: {
            asks: components["schemas"]["Ask"][];
        };
        AnswerRequest: {
            /** @enum {string} */
            decision: "approve" | "decline";
        };
        Spending: {
            run_id: string;
            period_days: number | null;
            limit_chf: components["schemas"]["Money"] | null;
            /** @description What the engine approved. The limit is enforced against this, so spend still awaiting the platform's acknowledgement is already reserved and cannot be spent twice. */
            approved_chf: components["schemas"]["Money"];
            /** @description The part the platform has accepted. Never proof of settlement, shipment or delivery — only that the authorization decision was accepted. */
            accepted_chf: components["schemas"]["Money"];
            /** @description Approved locally, not yet acknowledged. Reserved, not spendable again. */
            awaiting_platform_chf: components["schemas"]["Money"];
            remaining_chf: components["schemas"]["Money"] | null;
            platform_counter_chf: components["schemas"]["Money"] | null;
            /** @description Our ledger and the platform counter disagree (DEC-010). */
            mismatch: boolean;
        };
        MandateList: {
            mandates: components["schemas"]["Mandate"][];
            /** @description The active mandate, if any. */
            current_mandate_id: string | null;
        };
        MandateVersion: {
            review?: components["schemas"]["PermissionReview"];
            version: number;
            /** @enum {string} */
            change: "confirmed" | "tightened" | "revoked" | "expired";
            hard_rules: components["schemas"]["HardRule"][];
            /** @enum {string} */
            uncertainty_policy: "ask" | "decline" | "approve";
            /** Format: date-time */
            created_at: string;
        };
        MandateVersionList: {
            mandate_id: string;
            versions: components["schemas"]["MandateVersion"][];
        };
        RunList: {
            runs: components["schemas"]["Run"][];
            /** @description The run still in progress, if any. */
            current_run_id: string | null;
        };
        AskCreatedData: {
            authorization_id: string;
            merchant_name: string;
            billing_amount_chf: components["schemas"]["Money"];
            reasons: string[];
            /** Format: date-time */
            expires_at: string;
            can_approve: boolean;
        };
        AskResolvedData: {
            authorization_id: string;
            /** @enum {string} */
            outcome: "approved" | "declined" | "timed_out";
            /** @enum {string} */
            resolved_by: "customer" | "platform";
        };
        PaymentDecidedData: {
            authorization_id: string;
            /** @enum {string} */
            engine_verdict: "approve" | "decline" | "step_up";
            /** @enum {string} */
            final_state: "approved" | "declined" | "waiting";
            billing_amount_chf: components["schemas"]["Money"];
            customer_message: string;
        };
        MandateChangedData: {
            mandate_id: string;
            version: number;
            /** @enum {string} */
            status: "active" | "revoked" | "expired";
            /** @enum {string} */
            change: "confirmed" | "tightened" | "revoked" | "expired";
        };
        /** @description What the platform did with a decision already made (LEASH-130). Never a new verdict: the engine decided earlier, and this says only whether the answer was accepted. `accepted` is not evidence of settlement, shipment or delivery. */
        PaymentDeliveredData: {
            authorization_id: string;
            /** @enum {string} */
            delivery: "accepted" | "refused";
            platform_outcome: string | null;
            /** @enum {string} */
            final_state: "approved" | "declined" | "waiting" | "timed_out" | "not_sent";
        };
        IntegrityAlertData: {
            /** @enum {string} */
            kind: "spend_counter_mismatch" | "unsupported_mandate_rule" | "mandate_snapshot_mismatch" | "amount_mismatch" | "platform_delivery_mismatch";
            run_id: string | null;
            detail: string;
        };
        StreamEvent: {
            id: string;
            /** @enum {string} */
            type: "ask.created" | "ask.resolved" | "payment.decided" | "payment.delivered" | "mandate.changed" | "integrity.alert";
            /** Format: date-time */
            at: string;
            data: Record<string, never>;
        } & (unknown & unknown & unknown & unknown & unknown & unknown);
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDraft"];
                };
            };
        };
    };
    recordDraftMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                    reply: string;
                    context: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Unchanged permission with the appended exchange */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDraft"];
                };
            };
            /** @description Draft not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid exchange */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    answerDraftQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDraft"];
                };
            };
            /** @description Unknown draft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Already posted to Viseca (no draft updates there); start a new draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Bad body, not an open question, not one of its options, an empty answer, or an answer that doesn't answer its question (unclear, or gives nothing for that question); the reason is in the message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addDraftTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDraft"];
                };
            };
            /** @description Unknown draft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The draft is already at Viseca and can no longer change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    submitDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDraft"];
                };
            };
            /** @description Blocking questions remain */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mandate"];
                };
            };
            /** @description Not submitted yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDraft"];
                };
            };
            /** @description Unknown draft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listMandates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateList"];
                };
            };
        };
    };
    listMandateVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mandate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateVersionList"];
                };
            };
            /** @description Unknown mandate */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMandate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mandate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mandate"];
                };
            };
            /** @description Unknown mandate */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeMandate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mandate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mandate"];
                };
            };
            /** @description No such mandate */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Viseca did not answer; the mandate is still active */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    tightenMandate: {
        parameters: {
            query?: {
                /** @description Validate and render the proposed change without storing it or contacting the platform. */
                preview?: boolean;
            };
            header?: never;
            path: {
                mandate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TightenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mandate"];
                };
            };
            /** @description No such mandate */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not active, or Viseca refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Would loosen the permission */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Viseca did not answer */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The platform's test stories, without creating a mandate or run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioList"];
                };
            };
            /** @description Platform unavailable or invalid catalogue */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description No such mandate */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The mandate is not active, or Viseca refused the run */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Viseca did not answer */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description No such run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPayments: {
        parameters: {
            query?: {
                run_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentList"];
                };
            };
        };
    };
    getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDetail"];
                };
            };
            /** @description Unknown payment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAsks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskList"];
                };
            };
        };
    };
    answerAsk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            /** @description No such payment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No longer waiting (answered or expired) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A hard rule now fails */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The card is busy (its lock stayed taken); try again */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSpending: {
        parameters: {
            query?: {
                run_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Spending"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resume after this event. Initial state comes from the read endpoints. */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
