// The permission as a contract the customer reads before activating it (LEASH-146).
//
// Every sentence here is generated by the engine from the stored rule (DEC-045, LEASH-174): the model's
// prose never becomes consent text. This component only decides the order and the headings — it never
// writes, shortens or combines a boundary, because what is read out has to be what is enforced.
import type { HardRule, Mandate } from "../api/client";

export type ReviewLine = NonNullable<Mandate["review"]>["must_follow"][number];

/** One boundary at a time, in the order a customer checks them: what may be bought, for how much,
 *  where, how often, and what happens when something is unclear. */
const GROUPS = [["item", "Item"], ["price", "Price"], ["merchant", "Shop"],
                ["frequency", "How often"], ["uncertainty", "When unsure"]] as const;

export function perOrderLimit(rules: HardRule[]): number | null {
  const limits = rules.filter((r) => r.field === "authorization.billing_amount_chf" && !r.period_days
    && (r.scope ?? "purchase") === "purchase" && (r.currency ?? "CHF") === "CHF"
    && (r.operator === "<=" || r.operator === "<") && typeof r.value === "number");
  return limits.length ? Math.min(...limits.map((r) => Number(r.value))) : null;
}

export function permissionStatus(m: Mandate): string {
  if (m.status === "revoked" && !m.revocation?.platform_confirmed) return "Revocation unconfirmed";
  return m.status === "active" ? "Permission active" : m.status === "revoked" ? "Permission revoked" : "Permission expired";
}

/** The lines of one section under their headings. A line whose group this app does not know still
 *  appears — an unshown boundary is the one failure this review exists to prevent. */
function Grouped({ lines }: { lines: readonly ReviewLine[] }) {
  const known = new Set(GROUPS.map(([group]) => group as string));
  const rest = lines.filter((line) => !known.has(line.group));
  return <>
    {[...GROUPS.map(([group, heading]) => [heading, lines.filter((l) => l.group === group)] as const),
      ["Other", rest] as const]
      .filter(([, group]) => group.length > 0)
      .map(([heading, group]) => <div key={heading} className="boundary-part">
        <h3>{heading}</h3>
        <ul>{group.map((line) => <li key={line.text}>{line.text}</li>)}</ul>
      </div>)}
  </>;
}

export function PermissionSummary({ review, expanded = false }: { review: Mandate["review"]; expanded?: boolean }) {
  if (!review) return <p className="small">The rule summary could not be loaded. Check the recorded rules below.</p>;
  return <div className="permission-boundaries">
    {([["Must follow", review.must_follow], ["May choose", review.may_choose], ["Must ask", review.must_ask]] as const).map(([title, lines]) =>
      <section key={title} className="boundary-group" role="group" aria-label={title}>
        <h2>{title}</h2>
        {lines.length ? title === "May choose" && !expanded ? <details className="context-details"><summary>Choices within these boundaries</summary>
          <Grouped lines={lines} /></details> : <Grouped lines={lines} />
          : <p className="small">{title === "Must ask" ? "Uncertainty is handled by the rules above." : "No additional choices specified."}</p>}
      </section>)}
  </div>;
}
